"""Semilla de `game_configs`: los 177 parámetros de juego del contrato §5.

Ningún valor de balance vive en el código Python: todos nacen aquí y se leen en
ejecución con `ServicioConfig`. Esta tabla es la transcripción literal de §5 del
contrato (clave, valor inicial, `value_type` y `is_public`), con una descripción
en español por parámetro para que el panel de configuración sea legible.

Reglas que respeta esta semilla:

- El `value` se guarda como JSONB: un escalar JSON también es JSONB válido.
- `is_public` decide qué claves ve la app en `GET /api/v1/config/public`. Las
  reglas anti-abuso **nunca** son públicas.
- La siembra es idempotente: `ejecutar.py` actualiza la fila vigente de cada clave
  y solo abre una versión nueva cuando el valor o el tipo han cambiado.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

__all__ = ["PARAMETROS", "ParametroConfig", "por_clave"]


@dataclass(frozen=True, slots=True)
class ParametroConfig:
    """Un parámetro de `game_configs` tal como lo define el contrato §5."""

    key: str
    """Clave con espacio de nombres (`xp.lesson_completed`)."""

    value: Any
    """Valor inicial; se persiste como JSONB."""

    value_type: str
    """`int`, `decimal`, `bool`, `string`, `list` o `map`."""

    is_public: bool
    """`True` si la clave se expone en `GET /api/v1/config/public`."""

    description: str
    """Texto en español mostrado en el panel de configuración."""


#: Los 177 parámetros del contrato §5, en el orden de sus tablas.
PARAMETROS: tuple[ParametroConfig, ...] = (
    # -- §5.1 XP ---------------------------------------------------------
    ParametroConfig(
        key="xp.lesson_completed",
        value=50,
        value_type="int",
        is_public=True,
        description="XP base por completar una lección por primera vez.",
    ),
    ParametroConfig(
        key="xp.question_first_try",
        value=10,
        value_type="int",
        is_public=True,
        description="XP por acertar una pregunta al primer intento.",
    ),
    ParametroConfig(
        key="xp.question_second_try",
        value=4,
        value_type="int",
        is_public=True,
        description="XP por acertar una pregunta al segundo intento.",
    ),
    ParametroConfig(
        key="xp.question_cap_per_lesson",
        value=60,
        value_type="int",
        is_public=False,
        description="Tope de XP por preguntas dentro de una misma lección.",
    ),
    ParametroConfig(
        key="xp.challenge_completed",
        value=200,
        value_type="int",
        is_public=True,
        description="XP por superar un desafío (discrepancia D1: 200, no 250).",
    ),
    ParametroConfig(
        key="xp.assessment_passed",
        value=300,
        value_type="int",
        is_public=True,
        description="XP por aprobar la prueba del módulo.",
    ),
    ParametroConfig(
        key="xp.assessment_bonus_90",
        value=100,
        value_type="int",
        is_public=True,
        description="XP extra al obtener 90 % o más en la prueba del módulo.",
    ),
    ParametroConfig(
        key="xp.assessment_bonus_100",
        value=200,
        value_type="int",
        is_public=True,
        description="XP extra al obtener 100 % en la prueba del módulo.",
    ),
    ParametroConfig(
        key="xp.module_completed",
        value=200,
        value_type="int",
        is_public=True,
        description="XP por cerrar un módulo completo (discrepancia D2: 200, no 150).",
    ),
    ParametroConfig(
        key="xp.path_completed",
        value=1000,
        value_type="int",
        is_public=True,
        description="XP por completar una ruta de aprendizaje entera.",
    ),
    ParametroConfig(
        key="xp.review_completed",
        value=30,
        value_type="int",
        is_public=True,
        description="XP base por completar una sesión de repaso.",
    ),
    ParametroConfig(
        key="xp.review_per_correct",
        value=5,
        value_type="int",
        is_public=False,
        description="XP adicional por cada acierto dentro de un repaso.",
    ),
    ParametroConfig(
        key="xp.review_correct_cap",
        value=30,
        value_type="int",
        is_public=False,
        description="Tope del XP adicional por aciertos en un repaso.",
    ),
    ParametroConfig(
        key="xp.review_max_paid_per_day",
        value=3,
        value_type="int",
        is_public=False,
        description="Repasos que pagan XP por día local; los demás no pagan.",
    ),
    ParametroConfig(
        key="xp.first_activity_of_day",
        value=20,
        value_type="int",
        is_public=True,
        description="XP de bonificación por la primera actividad del día local.",
    ),
    ParametroConfig(
        key="xp.daily_goal",
        value=0,
        value_type="int",
        is_public=True,
        description="XP del objetivo diario: cero (D3, el objetivo paga oro, no XP).",
    ),
    ParametroConfig(
        key="xp.mission_daily_easy",
        value=40,
        value_type="int",
        is_public=True,
        description="XP de una misión diaria fácil.",
    ),
    ParametroConfig(
        key="xp.mission_daily_medium",
        value=100,
        value_type="int",
        is_public=True,
        description="XP de una misión diaria media.",
    ),
    ParametroConfig(
        key="xp.mission_daily_hard",
        value=180,
        value_type="int",
        is_public=True,
        description="XP de una misión diaria difícil.",
    ),
    ParametroConfig(
        key="xp.mission_weekly_medium",
        value=300,
        value_type="int",
        is_public=True,
        description="XP de una misión semanal media (fase 2).",
    ),
    ParametroConfig(
        key="xp.mission_weekly_hard",
        value=600,
        value_type="int",
        is_public=True,
        description="XP de una misión semanal difícil (fase 2).",
    ),
    ParametroConfig(
        key="xp.repeat_multipliers",
        value=[1.0, 0.2, 0.0],
        value_type="list",
        is_public=False,
        description="Multiplicadores por repetir una actividad: 100 %, 20 % y 0 % (regla A1).",
    ),
    ParametroConfig(
        key="xp.low_content_multiplier",
        value=0.5,
        value_type="decimal",
        is_public=False,
        description="Multiplicador de XP de una lección con material insuficiente (regla A8).",
    ),
    ParametroConfig(
        key="xp.streak_multiplier",
        value={"enabled": False},
        value_type="map",
        is_public=False,
        description="Multiplicador de XP por racha: desactivado (D4, la constancia se paga en oro).",
    ),
    ParametroConfig(
        key="xp.daily_softcap",
        value=[{"limit": 1500, "mult": 0.5}, {"limit": 3000, "mult": 0.1}],
        value_type="list",
        is_public=False,
        description="Tope blando diario de XP base: tramos y multiplicador aplicado (regla A5).",
    ),
    ParametroConfig(
        key="xp.min_time.lesson",
        value={"abs_seconds": 60, "ratio": 0.25},
        value_type="map",
        is_public=False,
        description="Tiempo mínimo plausible de una lección: segundos absolutos y razón sobre lo estimado.",
    ),
    ParametroConfig(
        key="xp.min_time.challenge",
        value={"abs_seconds": 90, "ratio": 0.25},
        value_type="map",
        is_public=False,
        description="Tiempo mínimo plausible de un desafío.",
    ),
    ParametroConfig(
        key="xp.min_time.assessment_per_question",
        value=20,
        value_type="int",
        is_public=False,
        description="Segundos mínimos por pregunta para que una prueba pague XP.",
    ),
    ParametroConfig(
        key="xp.min_time.answer_ms",
        value=2000,
        value_type="int",
        is_public=False,
        description="Milisegundos mínimos de respuesta para que una pregunta pague XP.",
    ),
    ParametroConfig(
        key="xp.attempt_ttl_hours",
        value=2,
        value_type="int",
        is_public=False,
        description="Horas de vida de un intento abierto antes de caducar.",
    ),
    # -- §5.2 Niveles ----------------------------------------------------
    ParametroConfig(
        key="level.base",
        value=80,
        value_type="int",
        is_public=True,
        description="Constante base de la curva de nivel global del personaje.",
    ),
    ParametroConfig(
        key="level.exponent",
        value=2.2,
        value_type="decimal",
        is_public=True,
        description="Exponente de la curva potencial de nivel.",
    ),
    ParametroConfig(
        key="level.max",
        value=50,
        value_type="int",
        is_public=True,
        description="Nivel máximo alcanzable.",
    ),
    ParametroConfig(
        key="level.round_to",
        value=10,
        value_type="int",
        is_public=True,
        description="Múltiplo al que se redondea el XP requerido de cada nivel.",
    ),
    ParametroConfig(
        key="level.rank_titles",
        value={
            "1": "Aprendiz",
            "5": "Iniciado/a",
            "10": "Escriba",
            "15": "Erudito/a",
            "20": "Adepto/a",
            "25": "Guardián/a del Saber",
            "30": "Sabio/a",
            "35": "Maestro/a",
            "40": "Gran Maestro/a",
            "45": "Archimaestro/a",
            "50": "Leyenda del Reino",
        },
        value_type="map",
        is_public=True,
        description="Títulos de rango del personaje por nivel de inicio de rango.",
    ),
    # -- §5.2 Niveles por conocimiento -----------------------------------
    ParametroConfig(
        key="knowledge.level.base",
        value=50,
        value_type="int",
        is_public=True,
        description="Constante base de la curva de nivel por conocimiento.",
    ),
    ParametroConfig(
        key="knowledge.level.exponent",
        value=2.2,
        value_type="decimal",
        is_public=True,
        description="Exponente de la curva de nivel por conocimiento.",
    ),
    ParametroConfig(
        key="knowledge.rank_titles",
        value={
            "1": "Novato/a en",
            "5": "Practicante de",
            "10": "Competente en",
            "15": "Avanzado/a en",
            "20": "Experto/a en",
            "30": "Maestro/a de",
        },
        value_type="map",
        is_public=True,
        description="Prefijos del título por conocimiento («Experto/a en»).",
    ),
    ParametroConfig(
        key="knowledge.master_title_requires_mastery",
        value=80,
        value_type="int",
        is_public=True,
        description="Dominio mínimo exigido para lucir el título de maestría del conocimiento.",
    ),
    ParametroConfig(
        key="knowledge.master_title_fallback",
        value="Veterano/a de",
        value_type="string",
        is_public=True,
        description="Título alternativo cuando no se alcanza el dominio de maestría.",
    ),
    # -- §5.3 Oro --------------------------------------------------------
    ParametroConfig(
        key="gold.welcome",
        value=100,
        value_type="int",
        is_public=True,
        description="Bolsa de bienvenida al crear el personaje.",
    ),
    ParametroConfig(
        key="gold.lesson_completed",
        value=20,
        value_type="int",
        is_public=True,
        description="Oro por completar una lección por primera vez.",
    ),
    ParametroConfig(
        key="gold.challenge_completed",
        value=60,
        value_type="int",
        is_public=True,
        description="Oro por superar un desafío.",
    ),
    ParametroConfig(
        key="gold.assessment_passed",
        value=100,
        value_type="int",
        is_public=True,
        description="Oro por aprobar la prueba del módulo.",
    ),
    ParametroConfig(
        key="gold.assessment_bonus_90",
        value=50,
        value_type="int",
        is_public=True,
        description="Oro extra al obtener 90 % o más en la prueba del módulo.",
    ),
    ParametroConfig(
        key="gold.assessment_bonus_100",
        value=100,
        value_type="int",
        is_public=True,
        description="Oro extra al obtener 100 % en la prueba del módulo.",
    ),
    ParametroConfig(
        key="gold.module_completed",
        value=80,
        value_type="int",
        is_public=True,
        description="Oro por cerrar un módulo completo.",
    ),
    ParametroConfig(
        key="gold.path_completed",
        value=500,
        value_type="int",
        is_public=True,
        description="Oro por completar una ruta entera.",
    ),
    ParametroConfig(
        key="gold.review_completed",
        value=10,
        value_type="int",
        is_public=True,
        description="Oro por completar una sesión de repaso.",
    ),
    ParametroConfig(
        key="gold.mission_daily_easy",
        value=10,
        value_type="int",
        is_public=True,
        description="Oro de una misión diaria fácil.",
    ),
    ParametroConfig(
        key="gold.mission_daily_medium",
        value=25,
        value_type="int",
        is_public=True,
        description="Oro de una misión diaria media.",
    ),
    ParametroConfig(
        key="gold.mission_daily_hard",
        value=50,
        value_type="int",
        is_public=True,
        description="Oro de una misión diaria difícil.",
    ),
    ParametroConfig(
        key="gold.mission_weekly_medium",
        value=100,
        value_type="int",
        is_public=True,
        description="Oro de una misión semanal media (fase 2).",
    ),
    ParametroConfig(
        key="gold.mission_weekly_hard",
        value=200,
        value_type="int",
        is_public=True,
        description="Oro de una misión semanal difícil (fase 2).",
    ),
    ParametroConfig(
        key="gold.level_up_bonus",
        value=50,
        value_type="int",
        is_public=True,
        description="Oro de bonificación al subir de nivel.",
    ),
    ParametroConfig(
        key="gold.rank_up_bonus",
        value=100,
        value_type="int",
        is_public=True,
        description="Oro de bonificación al estrenar rango.",
    ),
    ParametroConfig(
        key="gold.achievement_tiers",
        value={"bronze": 20, "silver": 60, "gold": 150, "single": 75},
        value_type="map",
        is_public=True,
        description="Oro por nivel de logro: bronce, plata, oro y logro de nivel único.",
    ),
    ParametroConfig(
        key="gold.daily_softcap",
        value=[{"limit": 500, "mult": 0.5}, {"limit": 1000, "mult": 0.1}],
        value_type="list",
        is_public=False,
        description="Tope blando diario de oro: tramos y multiplicador aplicado.",
    ),
    # -- §5.4 Tienda -----------------------------------------------------
    ParametroConfig(
        key="shop.price_by_rarity",
        value={"common": 150, "uncommon": 500, "rare": 1200, "epic": 3000, "legendary": 8000, "mythic": None},
        value_type="map",
        is_public=True,
        description="Precio en oro por rareza; los míticos no se venden.",
    ),
    ParametroConfig(
        key="shop.min_level_by_rarity",
        value={"common": 1, "uncommon": 3, "rare": 8, "epic": 15, "legendary": 25},
        value_type="map",
        is_public=True,
        description="Nivel mínimo del personaje para comprar cada rareza.",
    ),
    ParametroConfig(
        key="shop.unlock_level",
        value=3,
        value_type="int",
        is_public=True,
        description="Nivel en el que se abre la tienda al jugador.",
    ),
    ParametroConfig(
        key="shop.featured_max",
        value=4,
        value_type="int",
        is_public=True,
        description="Máximo de ofertas destacadas simultáneas en el escaparate.",
    ),
    ParametroConfig(
        key="shop.sellable_rarities",
        value=["common", "uncommon", "rare", "epic"],
        value_type="list",
        is_public=True,
        description="Rarezas que pueden ofertarse en la tienda del MVP.",
    ),
    ParametroConfig(
        key="shop.purchase_reversal_seconds",
        value=60,
        value_type="int",
        is_public=True,
        description="Ventana del botón «Deshacer» tras una compra.",
    ),
    ParametroConfig(
        key="shop.purchase_rate_limit_per_minute",
        value=10,
        value_type="int",
        is_public=False,
        description="Compras por minuto admitidas a un mismo usuario.",
    ),
    ParametroConfig(
        key="shop.streak_protector",
        value={"enabled": False, "price": 300, "max_held": 1, "cooldown_days": 7},
        value_type="map",
        is_public=False,
        description="Protector de racha: desactivado en el MVP (fase 2).",
    ),
    # -- §5.4 Inventario -------------------------------------------------
    ParametroConfig(
        key="items.slots_active",
        value=["head", "body", "cape", "gloves", "boots", "weapon", "offhand", "accessory"],
        value_type="list",
        is_public=True,
        description="Ranuras de equipamiento activas en los datos.",
    ),
    ParametroConfig(
        key="items.slots_reserved",
        value=["pet", "mount"],
        value_type="list",
        is_public=True,
        description="Ranuras reservadas para fases posteriores (mascota y montura).",
    ),
    ParametroConfig(
        key="items.rarity_colors",
        value={
            "common": "#9AA3AE",
            "uncommon": "#4CAF7D",
            "rare": "#4A90D9",
            "epic": "#8E6CC8",
            "legendary": "#E0A33A",
            "mythic": "#D9534F",
        },
        value_type="map",
        is_public=True,
        description="Color del marco de cada rareza (referencia de UX).",
    ),
    ParametroConfig(
        key="items.derived_templates",
        value=["tpl_capa_estudiante", "tpl_capa_maestro", "tpl_insignia_perfeccion"],
        value_type="list",
        is_public=False,
        description="Códigos de las plantillas que se materializan por conocimiento.",
    ),
    ParametroConfig(
        key="items.canonical_area_slugs",
        value=[
            "sql",
            "bigquery",
            "data_engineering",
            "inteligencia_artificial",
            "gcp",
            "python",
            "business_intelligence",
        ],
        value_type="list",
        is_public=False,
        description="Vocabulario canónico de conocimientos con ítem curado propio.",
    ),
    ParametroConfig(
        key="items.mastered_threshold",
        value=80,
        value_type="int",
        is_public=True,
        description="Dominio a partir del cual un conocimiento cuenta como dominado.",
    ),
    # -- §5.5 Dominio ----------------------------------------------------
    ParametroConfig(
        key="mastery.weight.difficulty",
        value={"easy": 1.0, "medium": 1.5, "hard": 2.0},
        value_type="map",
        is_public=False,
        description="Peso de la evidencia según la dificultad de la pregunta.",
    ),
    ParametroConfig(
        key="mastery.weight.context",
        value={"lesson": 1.0, "practice": 1.0, "review": 1.0, "challenge": 1.5, "assessment": 2.0},
        value_type="map",
        is_public=False,
        description="Peso de la evidencia según el contexto en que se respondió.",
    ),
    ParametroConfig(
        key="mastery.weight.retake",
        value=[1.0, 0.6, 0.3],
        value_type="list",
        is_public=False,
        description="Peso decreciente de las repeticiones de una misma pregunta.",
    ),
    ParametroConfig(
        key="mastery.correctness_second_try",
        value=0.5,
        value_type="decimal",
        is_public=False,
        description="Crédito de acierto que se concede a la respuesta correcta al segundo intento.",
    ),
    ParametroConfig(
        key="mastery.recency_half_life_days",
        value=30,
        value_type="int",
        is_public=False,
        description="Semivida en días del peso por recencia de la evidencia.",
    ),
    ParametroConfig(
        key="mastery.prior_m",
        value=3,
        value_type="decimal",
        is_public=False,
        description="Masa del prior bayesiano del dominio por tema.",
    ),
    ParametroConfig(
        key="mastery.prior_p0",
        value=0.5,
        value_type="decimal",
        is_public=False,
        description="Probabilidad previa de acierto antes de tener evidencia.",
    ),
    ParametroConfig(
        key="mastery.evidence_window",
        value={"max_items": 40, "max_days": 180},
        value_type="map",
        is_public=False,
        description="Ventana de evidencia considerada: máximo de ítems y de días.",
    ),
    ParametroConfig(
        key="mastery.coverage_floor",
        value=0.6,
        value_type="decimal",
        is_public=False,
        description="Cobertura mínima de objetivos para que el dominio no se penalice.",
    ),
    ParametroConfig(
        key="mastery.decay",
        value={
            "grace_days": 7,
            "floor": 0.6,
            "half_life_days": 60,
            "stability_factor": 1.5,
            "half_life_max_days": 365,
        },
        value_type="map",
        is_public=False,
        description="Curva de olvido: días de gracia, suelo, semivida, estabilidad y tope.",
    ),
    ParametroConfig(
        key="mastery.module.weight_topics",
        value=0.7,
        value_type="decimal",
        is_public=False,
        description="Peso de los temas en el dominio del módulo.",
    ),
    ParametroConfig(
        key="mastery.module.weight_assessment",
        value=0.3,
        value_type="decimal",
        is_public=False,
        description="Peso de la prueba en el dominio del módulo.",
    ),
    ParametroConfig(
        key="mastery.assessment.pass_score",
        value=70,
        value_type="int",
        is_public=True,
        description="Puntaje mínimo para aprobar la prueba del módulo.",
    ),
    ParametroConfig(
        key="mastery.assessment.distinction_score",
        value=90,
        value_type="int",
        is_public=True,
        description="Puntaje que otorga distinción en la prueba del módulo.",
    ),
    ParametroConfig(
        key="mastery.assessment.retake_penalty",
        value={"per_attempt": 0.05, "max": 0.15},
        value_type="map",
        is_public=False,
        description="Penalización por intento repetido de la prueba y su tope.",
    ),
    ParametroConfig(
        key="mastery.assessment.cooldown_hours",
        value=[4, 24, 48],
        value_type="list",
        is_public=True,
        description="Horas de espera entre intentos sucesivos de la prueba.",
    ),
    ParametroConfig(
        key="mastery.assessment.max_attempts_per_day",
        value=2,
        value_type="int",
        is_public=True,
        description="Intentos de prueba admitidos por día local.",
    ),
    ParametroConfig(
        key="mastery.assessment.bank_ratio",
        value=2.5,
        value_type="decimal",
        is_public=False,
        description="Tamaño del banco de preguntas respecto de las que se muestran.",
    ),
    ParametroConfig(
        key="mastery.assessment.max_overlap",
        value=0.3,
        value_type="decimal",
        is_public=False,
        description="Solape máximo de preguntas entre dos intentos.",
    ),
    ParametroConfig(
        key="mastery.assessment.question_count",
        value=10,
        value_type="int",
        is_public=True,
        description="Preguntas que se presentan en cada intento de la prueba.",
    ),
    ParametroConfig(
        key="mastery.threshold.mastered",
        value=80,
        value_type="int",
        is_public=True,
        description="Umbral de dominio a partir del cual algo se considera dominado.",
    ),
    ParametroConfig(
        key="mastery.threshold.at_risk",
        value=70,
        value_type="int",
        is_public=True,
        description="Umbral por debajo del cual el dominio queda en riesgo.",
    ),
    ParametroConfig(
        key="mastery.threshold.weak_practice",
        value=50,
        value_type="int",
        is_public=False,
        description="Umbral que marca un tema como débil y digno de práctica.",
    ),
    ParametroConfig(
        key="mastery.weak_min_evidence",
        value=5,
        value_type="int",
        is_public=False,
        description="Evidencias mínimas antes de declarar débil un tema.",
    ),
    ParametroConfig(
        key="mastery.review.stability_min_score",
        value=70,
        value_type="int",
        is_public=False,
        description="Puntaje mínimo del repaso para que aumente la estabilidad.",
    ),
    ParametroConfig(
        key="mastery.review.questions",
        value={"min": 4, "max": 8},
        value_type="map",
        is_public=True,
        description="Preguntas mínimas y máximas de una sesión de repaso.",
    ),
    ParametroConfig(
        key="mastery.weakness_rules",
        value={
            "R1_errors_in_last_10": 3,
            "R2_accuracy_lt": 50,
            "R2_min_attempts": 5,
            "R3_assessment_topic_lt": 60,
            "R4_time_multiplier": 2.0,
            "R4_min_questions": 2,
            "R5_objective_zero_of": 3,
        },
        value_type="map",
        is_public=False,
        description="Umbrales de las cinco reglas de detección de debilidades.",
    ),
    ParametroConfig(
        key="mastery.area_mastered_requires_completed_path",
        value=True,
        value_type="bool",
        is_public=True,
        description="Dominar un conocimiento exige además una ruta completada.",
    ),
    # -- §5.6 Racha ------------------------------------------------------
    ParametroConfig(
        key="streak.min_daily_educational_xp",
        value=30,
        value_type="int",
        is_public=True,
        description="XP educativo mínimo que da por activo el día.",
    ),
    ParametroConfig(
        key="streak.sync_tolerance_min",
        value=10,
        value_type="int",
        is_public=False,
        description="Minutos de tolerancia entre el reloj del cliente y el del servidor.",
    ),
    ParametroConfig(
        key="streak.grace_per_month",
        value=1,
        value_type="int",
        is_public=True,
        description="Días de gracia disponibles cada mes natural.",
    ),
    ParametroConfig(
        key="streak.travel_skip_per_30d",
        value=1,
        value_type="int",
        is_public=False,
        description="Ajustes por viaje admitidos cada treinta días.",
    ),
    ParametroConfig(
        key="streak.tz_change_min_delta_h",
        value=3,
        value_type="int",
        is_public=False,
        description="Diferencia horaria mínima para tratar un cambio como viaje.",
    ),
    ParametroConfig(
        key="streak.tz_changes_max_per_24h",
        value=1,
        value_type="int",
        is_public=False,
        description="Cambios de zona horaria aceptados en veinticuatro horas.",
    ),
    ParametroConfig(
        key="streak.milestones",
        value=[7, 14, 30, 60, 100, 365],
        value_type="list",
        is_public=True,
        description="Longitudes de racha que celebran un hito.",
    ),
    ParametroConfig(
        key="streak.repeat_milestone_every",
        value=50,
        value_type="int",
        is_public=True,
        description="Cada cuántos días se repite el hito tras el último fijo.",
    ),
    ParametroConfig(
        key="streak.milestone_rewards",
        value={
            "7": {"xp": 50, "gold": 50, "item_code": "antorcha_constancia"},
            "14": {"xp": 100, "gold": 100, "item_code": "botas_caminante"},
            "30": {"xp": 200, "gold": 200, "item_code": "capa_llamas_persistentes"},
            "60": {"xp": 300, "gold": 300, "item_code": None},
            "100": {"xp": 500, "gold": 500, "item_code": "corona_fuego_eterno"},
            "365": {"xp": 1000, "gold": 1000, "item_code": None},
            "repeat": {"xp": 250, "gold": 250, "item_code": None},
        },
        value_type="map",
        is_public=True,
        description="Recompensa de cada hito de racha: XP, oro y objeto.",
    ),
    # -- §5.6 Objetivo diario --------------------------------------------
    ParametroConfig(
        key="goal.default",
        value={"type": "minutos", "target": 20},
        value_type="map",
        is_public=True,
        description="Objetivo diario por defecto al crear la cuenta (D10: minutos).",
    ),
    ParametroConfig(
        key="goal.minutes.options",
        value=[10, 20, 30, 45],
        value_type="list",
        is_public=True,
        description="Opciones de objetivo diario medido en minutos.",
    ),
    ParametroConfig(
        key="goal.activities.options",
        value=[1, 3, 5, 8],
        value_type="list",
        is_public=True,
        description="Opciones de objetivo diario medido en actividades.",
    ),
    ParametroConfig(
        key="goal.xp.options",
        value=[50, 100, 200, 350],
        value_type="list",
        is_public=True,
        description="Opciones de objetivo diario medido en XP.",
    ),
    ParametroConfig(
        key="goal.change_effective",
        value="next_day",
        value_type="string",
        is_public=True,
        description="Cuándo entra en vigor una bajada de objetivo; las subidas son inmediatas.",
    ),
    ParametroConfig(
        key="goal.activity_units",
        value={
            "lesson": 1,
            "questions_block": 1,
            "questions_per_block": 5,
            "review": 1,
            "challenge": 1,
            "assessment": 2,
        },
        value_type="map",
        is_public=True,
        description="Unidades de actividad que aporta cada hecho educativo.",
    ),
    ParametroConfig(
        key="goal.bonus_gold_base",
        value=10,
        value_type="int",
        is_public=True,
        description="Oro base del bono por cumplir el objetivo diario.",
    ),
    ParametroConfig(
        key="goal.bonus_gold_cap_days",
        value=20,
        value_type="int",
        is_public=True,
        description="Días de racha a partir de los cuales el bono deja de crecer.",
    ),
    ParametroConfig(
        key="goal.adapt.window_days",
        value=14,
        value_type="int",
        is_public=False,
        description="Ventana de días que observa la recomendación de objetivo.",
    ),
    ParametroConfig(
        key="goal.adapt.up_rule",
        value={"met_days_gte": 12, "ratio_gte": 1.5},
        value_type="map",
        is_public=False,
        description="Condiciones para recomendar subir el objetivo diario.",
    ),
    ParametroConfig(
        key="goal.adapt.down_rule",
        value={"met_days_lte": 4, "active_days_gte": 8},
        value_type="map",
        is_public=False,
        description="Condiciones para recomendar bajar el objetivo diario.",
    ),
    ParametroConfig(
        key="goal.adapt.cooldown_days",
        value=14,
        value_type="int",
        is_public=False,
        description="Días de espera entre dos recomendaciones de objetivo.",
    ),
    ParametroConfig(
        key="goal.adapt.rejected_cooldown_days",
        value=28,
        value_type="int",
        is_public=False,
        description="Días de espera tras rechazar una recomendación.",
    ),
    # -- §5.6 Tiempo de estudio ------------------------------------------
    ParametroConfig(
        key="time.heartbeat_s",
        value=30,
        value_type="int",
        is_public=True,
        description="Cadencia del latido de tiempo de estudio que envía el cliente.",
    ),
    ParametroConfig(
        key="time.max_tick_s",
        value=60,
        value_type="int",
        is_public=False,
        description="Segundos máximos que puede aportar un solo latido.",
    ),
    ParametroConfig(
        key="time.idle_cutoff_s",
        value=120,
        value_type="int",
        is_public=False,
        description="Inactividad a partir de la cual deja de contarse el tiempo.",
    ),
    ParametroConfig(
        key="time.max_activity_multiplier",
        value=3,
        value_type="int",
        is_public=False,
        description="Tope del tiempo contable respecto del estimado de la actividad.",
    ),
    ParametroConfig(
        key="time.session_idle_timeout_min",
        value=10,
        value_type="int",
        is_public=False,
        description="Minutos de inactividad que cierran la sesión de estudio.",
    ),
    # -- §5.7 Misiones ---------------------------------------------------
    ParametroConfig(
        key="missions.daily.count",
        value=3,
        value_type="int",
        is_public=True,
        description="Misiones diarias activas al mismo tiempo.",
    ),
    ParametroConfig(
        key="missions.daily.tier_mix",
        value=["easy", "medium", "variety"],
        value_type="list",
        is_public=False,
        description="Mezcla de dificultades del trío diario.",
    ),
    ParametroConfig(
        key="missions.daily.no_repeat_days",
        value=1,
        value_type="int",
        is_public=False,
        description="Días sin repetir la misma plantilla de misión.",
    ),
    ParametroConfig(
        key="missions.claim.auto_on_expiry",
        value=True,
        value_type="bool",
        is_public=True,
        description="Al expirar el periodo se reclaman solas las misiones completadas.",
    ),
    ParametroConfig(
        key="missions.path.per_path",
        value=3,
        value_type="int",
        is_public=True,
        description="Misiones especiales que se instancian por cada ruta.",
    ),
    ParametroConfig(
        key="missions.path.max_paths_shown",
        value=5,
        value_type="int",
        is_public=True,
        description="Rutas con misiones visibles antes de plegar el resto.",
    ),
    ParametroConfig(
        key="missions.weekly.enabled",
        value=False,
        value_type="bool",
        is_public=True,
        description="Misiones semanales activas; desactivadas en el MVP.",
    ),
    ParametroConfig(
        key="missions.reroll.per_day",
        value=0,
        value_type="int",
        is_public=True,
        description="Cambios de misión permitidos al día (fase 2).",
    ),
    # -- §5.7 Logros -----------------------------------------------------
    ParametroConfig(
        key="achievements.reward.bronze",
        value={"xp": 25, "gold": 20},
        value_type="map",
        is_public=True,
        description="Recompensa por defecto del nivel bronce de un logro.",
    ),
    ParametroConfig(
        key="achievements.reward.silver",
        value={"xp": 75, "gold": 60},
        value_type="map",
        is_public=True,
        description="Recompensa por defecto del nivel plata de un logro.",
    ),
    ParametroConfig(
        key="achievements.reward.gold",
        value={"xp": 200, "gold": 150},
        value_type="map",
        is_public=True,
        description="Recompensa por defecto del nivel oro de un logro.",
    ),
    ParametroConfig(
        key="achievements.reward.single",
        value={"xp": 100, "gold": 75},
        value_type="map",
        is_public=True,
        description="Recompensa por defecto de un logro de nivel único.",
    ),
    ParametroConfig(
        key="achievements.near_unlock_pct",
        value=80,
        value_type="int",
        is_public=True,
        description="Progreso desde el cual se sugiere un logro como «casi lo tienes».",
    ),
    # -- §5.7 Notificaciones ---------------------------------------------
    ParametroConfig(
        key="notifications.reminder.default_hour",
        value="19:00",
        value_type="string",
        is_public=True,
        description="Hora local por defecto del recordatorio diario.",
    ),
    ParametroConfig(
        key="notifications.reminder.offset_min",
        value=45,
        value_type="int",
        is_public=False,
        description="Desplazamiento en minutos sobre la hora habitual de estudio.",
    ),
    ParametroConfig(
        key="notifications.reminder.window",
        value={"start": "08:00", "end": "21:30"},
        value_type="map",
        is_public=False,
        description="Franja horaria en la que puede enviarse el recordatorio.",
    ),
    ParametroConfig(
        key="notifications.last_call.hour",
        value="21:30",
        value_type="string",
        is_public=True,
        description="Hora del aviso final para no perder la racha.",
    ),
    ParametroConfig(
        key="notifications.last_call.min_streak",
        value=7,
        value_type="int",
        is_public=False,
        description="Racha mínima para recibir el aviso final.",
    ),
    ParametroConfig(
        key="notifications.quiet_hours",
        value={"start": "22:00", "end": "08:00"},
        value_type="map",
        is_public=True,
        description="Franja de silencio en la que no se envía ninguna notificación.",
    ),
    ParametroConfig(
        key="notifications.max_per_day.streak_goal",
        value=2,
        value_type="int",
        is_public=False,
        description="Máximo diario de avisos de racha y objetivo.",
    ),
    ParametroConfig(
        key="notifications.max_per_day.total",
        value=3,
        value_type="int",
        is_public=False,
        description="Máximo diario de notificaciones de cualquier tipo.",
    ),
    ParametroConfig(
        key="notifications.reactivation_days",
        value=[3, 7, 30],
        value_type="list",
        is_public=False,
        description="Días de inactividad que disparan un aviso de reactivación.",
    ),
    # -- §5.8 Contenido --------------------------------------------------
    ParametroConfig(
        key="content.lesson.target_minutes",
        value={"min": 5, "max": 15, "default": 9},
        value_type="map",
        is_public=True,
        description="Duración objetivo de una lección, en minutos.",
    ),
    ParametroConfig(
        key="content.module.topics",
        value={"min": 2, "max": 6},
        value_type="map",
        is_public=False,
        description="Temas mínimos y máximos por módulo.",
    ),
    ParametroConfig(
        key="content.path.modules",
        value={"min": 4, "max": 10},
        value_type="map",
        is_public=False,
        description="Módulos mínimos y máximos por ruta.",
    ),
    ParametroConfig(
        key="content.topic.lessons",
        value={"min": 1, "max": 3},
        value_type="map",
        is_public=False,
        description="Lecciones mínimas y máximas por tema.",
    ),
    ParametroConfig(
        key="content.questions_per_topic",
        value=5,
        value_type="int",
        is_public=False,
        description="Preguntas que se generan por tema.",
    ),
    ParametroConfig(
        key="content.open_questions_per_lesson_max",
        value=1,
        value_type="int",
        is_public=False,
        description="Preguntas abiertas como máximo por lección.",
    ),
    ParametroConfig(
        key="content.challenges_per_module_max",
        value=1,
        value_type="int",
        is_public=False,
        description="Desafíos como máximo por módulo.",
    ),
    ParametroConfig(
        key="content.difficulty_distribution",
        value={"easy": 0.5, "medium": 0.35, "hard": 0.15},
        value_type="map",
        is_public=False,
        description="Reparto objetivo de dificultad de las preguntas.",
    ),
    ParametroConfig(
        key="content.mvp_question_types",
        value=[
            "multiple_choice",
            "true_false",
            "fill_blank",
            "matching",
            "ordering",
            "open_short",
            "sql_exercise",
        ],
        value_type="list",
        is_public=True,
        description="Tipos de pregunta habilitados en el MVP (D13: siete).",
    ),
    ParametroConfig(
        key="content.seed_paths_target",
        value=5,
        value_type="int",
        is_public=False,
        description="Rutas del Reino que el catálogo semilla aspira a ofrecer.",
    ),
    # -- §5.8 Ingesta ----------------------------------------------------
    ParametroConfig(
        key="ingestion.max_file_mb",
        value=25,
        value_type="int",
        is_public=True,
        description="Tamaño máximo de un archivo subido, en megabytes.",
    ),
    ParametroConfig(
        key="ingestion.max_pdf_pages",
        value=300,
        value_type="int",
        is_public=True,
        description="Páginas máximas de un PDF aceptado.",
    ),
    ParametroConfig(
        key="ingestion.max_files_per_path",
        value=10,
        value_type="int",
        is_public=True,
        description="Archivos máximos asociados a una ruta.",
    ),
    ParametroConfig(
        key="ingestion.max_corpus_tokens",
        value=150000,
        value_type="int",
        is_public=False,
        description="Tokens máximos del corpus de una ruta.",
    ),
    ParametroConfig(
        key="ingestion.min_words_for_path",
        value=300,
        value_type="int",
        is_public=True,
        description="Palabras mínimas de material para diseñar una ruta.",
    ),
    ParametroConfig(
        key="ingestion.max_ingest_minutes",
        value=5,
        value_type="int",
        is_public=False,
        description="Minutos máximos que puede durar una ingesta.",
    ),
    ParametroConfig(
        key="ingestion.chunk",
        value={"target_tokens": 450, "max_tokens": 800, "min_tokens": 80, "overlap_pct": 0.12},
        value_type="map",
        is_public=False,
        description="Troceado del material: tokens objetivo, máximo, mínimo y solape.",
    ),
    ParametroConfig(
        key="ingestion.scanned_pdf_min_chars_per_page",
        value=50,
        value_type="int",
        is_public=False,
        description="Caracteres por página bajo los cuales el PDF se considera escaneado.",
    ),
    ParametroConfig(
        key="ingestion.purge_after_days",
        value=30,
        value_type="int",
        is_public=False,
        description="Días tras los cuales se purga el material original.",
    ),
    # -- §5.8 IA ---------------------------------------------------------
    ParametroConfig(
        key="ai.models",
        value={
            "path_design": "claude-opus-5",
            "lesson": "claude-sonnet-5",
            "questions": "claude-sonnet-5",
            "judge": "claude-haiku-4-5",
            "judge_escalation": "claude-sonnet-5",
            "narrative": "claude-haiku-4-5",
            "groundedness": "claude-haiku-4-5",
        },
        value_type="map",
        is_public=False,
        description="Modelo de Claude asignado a cada tarea de generación.",
    ),
    ParametroConfig(
        key="ai.embeddings",
        value={"provider": "voyage", "model": "voyage-3-lite", "dimensions": 512, "batch_size": 128},
        value_type="map",
        is_public=False,
        description="Proveedor, modelo, dimensiones y lote de los embeddings.",
    ),
    ParametroConfig(
        key="ai.retrieval",
        value={
            "vector_top_k": 20,
            "lexical_top_k": 20,
            "rrf_k": 60,
            "design_bonus": 0.02,
            "final_top_k": 10,
            "reexplain_top_k": 6,
            "min_score_ratio": 0.4,
        },
        value_type="map",
        is_public=False,
        description="Parámetros de la recuperación híbrida (vectorial más léxica).",
    ),
    ParametroConfig(
        key="ai.judge",
        value={
            "correct_score": 70,
            "partial_score": 40,
            "min_confidence": 0.6,
            "benefit_of_doubt_score": 60,
            "min_words": 3,
        },
        value_type="map",
        is_public=False,
        description="Umbrales del juez de respuestas abiertas.",
    ),
    ParametroConfig(
        key="ai.quotas_per_day",
        value={
            "path_designs": 2,
            "active_paths": 3,
            "re_explanations": 10,
            "judged_answers": 50,
            "content_reports": 10,
            "upload_mb": 100,
            "module_regenerations": 2,
        },
        value_type="map",
        is_public=True,
        description="Cuotas diarias de uso de IA por usuario.",
    ),
    ParametroConfig(
        key="ai.global_budget_usd_per_day",
        value=30,
        value_type="int",
        is_public=False,
        description="Presupuesto global de IA en dólares por día.",
    ),
    ParametroConfig(
        key="ai.budget_thresholds",
        value=[0.8, 1.0],
        value_type="list",
        is_public=False,
        description="Fracciones del presupuesto que disparan una alerta.",
    ),
    ParametroConfig(
        key="ai.sql_sandbox",
        value={
            "engine": "duckdb",
            "timeout_ms": 2000,
            "memory_limit_mb": 256,
            "max_rows": 10000,
            "max_tables": 5,
            "max_rows_per_table": 200,
        },
        value_type="map",
        is_public=False,
        description="Límites del sandbox DuckDB que corrige los ejercicios de SQL.",
    ),
    ParametroConfig(
        key="ai.generation_targets",
        value={"skeleton_seconds": 90, "first_module_seconds": 90},
        value_type="map",
        is_public=False,
        description="Objetivos de latencia de la generación de contenido.",
    ),
)


def por_clave() -> dict[str, ParametroConfig]:
    """Índice `clave -> parámetro` para consultas puntuales de la semilla."""
    return {parametro.key: parametro for parametro in PARAMETROS}
